security_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  namespace :admins do
    resources :webcams, only: [:index] do
      collection do
        get 'delete_images'
        get 'video'
        get 'status'
        get 'security'
        post 'toggle'
      end
    end
  end

  namespace :api do
    resource :webcams, only: [:create] do
      collection do
        get 'contacts'
      end
    end
  end

  root 'home#index'
end

security_app/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

security_app/app/models/webcam.rb
class Webcam < ActiveRecord::Base
  has_attached_file :image, PaperclipStorage[:webcams]

  Paperclip.interpolates :camera do |attachment, style|
    image = attachment.instance
    "#{image.camera}"
  end

  Paperclip.interpolates :image_file_name do |attachment, style|
    image = attachment.instance
    "#{image.image_file_name}"
  end

  def authenticated_s3_get_url(options = {})
    options.reverse_merge!(expires: 10.minutes)

    bucket = AWS::S3::Bucket.new(image.options[:bucket])

    s3 = AWS::S3::S3Object.new(bucket, image.path)
    s3.url_for(:get, options).to_s
  end

  def error_messages
    messages = self.errors.messages.collect do |attr, msg|
      "#{attr.to_s.humanize} #{msg.first}"
    end
    messages.join(", ")
  end
end

security_app/app/controllers/admins/webcams_controller.rb
class Admins::WebcamsController < ApplicationController
  before_action :authenticate_admin!

  def index
    webcam = Webcam.where(image_content_type: "image/jpeg")

    @camera = webcam.where("camera = ?", query)
  end

  def video
    webcam = Webcam.where(image_content_type: "video/mp4")

    @camera = webcam.where("camera = ?", query)
  end

  def delete_images
    Webcam.destroy_all
    redirect_to admins_webcams_path, notice: "All images deleted"
  end

  def status
    render text: SecurityApi.status
  end

  def toggle
    if status_valid?
      resp = SecurityApi.action(params["status"])
      render text: resp, status: resp
    else
      render text: 422, status: 422
    end
  end

  def security; end

  private

  def status_valid?
    ["armed", "disarmed"].include?(params["status"])
  end

  def query
    params["q"] || ""
  end
end

security_app/app/controllers/api/webcams_controller.rb
class Api::WebcamsController < ApplicationController
  http_basic_authenticate_with name: "name", password: "password"

  protect_from_forgery except: :create

  def contacts
    render plain: contact_list.join(",")
  end

  def create
    @image = Webcam.new(webcam_params)
    if @image.save
      render nothing: true, status: 201
    else
      render json: { errors: @image.errors.full_messages }, status: 422
    end
  end

  private

  def webcam_params
    params.require(:webcam).permit(
      :camera, :image_file_name, :image_content_type, :image_file_size
    )
  end

  def contact_list
    %w(
      number@messaging.sprintpcs.com
      number@tmomail.net
      email@gmail.com
    )
  end
end

security_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  force_ssl if: :ssl_configured?
  protect_from_forgery with: :exception

  def default_url_options(options={})
    options.merge!(protocol: 'https') if Rails.env.production?
    options
  end

  protected

  def admin_only
    unless current_admin.admin?
      redirect_to admins_webcams_path, alert: "Access denied."
    end
  end

  private

  def ssl_configured?
    Rails.env.production?
  end

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.class == Admin
      admins_webcams_path
    else
      super
    end
  end
end

security_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

security_app/app/helpers/application_helper.rb
module ApplicationHelper
end

security_app/app/views/admins/webcams/_delete_images_videos.html.erb
<p>
<%= link_to "Delete All Images and Videos", delete_images_admins_webcams_path, class: "button", data: { confirm: "Are you sure?" } %>
</p>

security_app/app/views/admins/webcams/_image_gallery.html.erb
<% if images %>
  <ul class="clearing-thumbs small-block-grid-6" data-clearing>
    <% images.each do |image| %>
      <li><%= link_to image_tag(image.authenticated_s3_get_url), image.authenticated_s3_get_url %></li>
    <% end %>
  </ul>
<% end %>

security_app/app/views/admins/webcams/_security.html.erb
<p><a href="#" class="button" id="security"></a></p>
<div id="security-error" data-alert class="alert-box alert round" style="display: none;"></div>

security_app/app/views/admins/webcams/_video_gallery.html.erb
<% if videos %>
  <% videos.each do |video| %>
    <div class="flex-video">
      <iframe src="<%= video.authenticated_s3_get_url %>" frameborder="0" allowFullScreen></iframe>
    </div>
  <% end %>
<% end %>

security_app/app/views/admins/webcams/index.html.erb
<h1>Webcam Image Gallery</h1>
<%= render partial: "security", locals: { status: @status } %>
<p><%= link_to "Webcam Video Gallery", video_admins_webcams_path(q: "camera1") %></p>
<%= render partial: "delete_images_videos" %>
<dl class="sub-nav cameras">
  <dt>Camera:</dt>
  <dd class="camera1 filter">
    <%= link_to "One", admins_webcams_path(q: "camera1") %>
  </dd>
  <dd class="camera2 filter">
    <%= link_to "Two", admins_webcams_path(q: "camera2") %>
  </dd>
  <dd class="camera3 filter">
    <%= link_to "Three", admins_webcams_path(q: "camera3") %>
  </dd>
</dl>
<%= render partial: "image_gallery", locals: { images: @camera } %>

security_app/app/views/admins/webcams/security.html.erb
<h1>Security System</h1>
<%= render partial: "security", locals: { status: @status } %>

security_app/app/views/admins/webcams/video.html.erb
<h1>Webcam Video Gallery</h1>
<%= render partial: "security", locals: { status: @status } %>
<p><%= link_to "Webcam Image Gallery", admins_webcams_path(q: "camera1") %></p>
<%= render partial: "delete_images_videos" %>
<dl class="sub-nav cameras">
  <dt>Camera:</dt>
  <dd class="camera1 filter">
    <%= link_to "One", video_admins_webcams_path(q: "camera1") %>
  </dd>
  <dd class="camera2 filter">
    <%= link_to "Two", video_admins_webcams_path(q: "camera2") %>
  </dd>
  <dd class="camera3 filter">
    <%= link_to "Three", video_admins_webcams_path(q: "camera3") %>
  </dd>
</dl>
<%= render partial: "video_gallery", locals: { videos: @camera } %>

security_app/app/views/home/index.html.erb
<h1>Welcome</h1>

security_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: "shared/top_nav" %>
    <%= render partial: "shared/alert" %>
    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
    <% if admin_signed_in? %>
      <%= javascript_include_tag "admin.js" %>
    <% end %>
  </body>
</html>

security_app/app/views/shared/_admin_nav.html.erb
<% if current_admin %>
  <li><%= link_to "Webcams", admins_webcams_path %></li>
  <li><%= link_to current_admin.email, "#" %></li>
<% end %>
<li><%= link_to "Log Out", destroy_admin_session_path, method: :delete %></li>

security_app/app/views/shared/_alert.html.erb
<% if notice %>
  <div data-alert="" class="alert-box success">
    <%= notice %>
    <a href="" class="close">x</a>
  </div>
<% end %>

<% if alert %>
  <div data-alert="" class="alert-box alert">
    <%= alert %>
    <a href="" class="close">x</a>
  </div>
<% end %>

security_app/app/views/shared/_top_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Security", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon">
      <%= link_to "#" do %>
        <span>Menu</span>
      <% end %>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <% if admin_signed_in? %>
        <%= render partial: "shared/admin_nav" %>
      <% else %>
        <li><%= link_to "Log In", new_admin_session_path %></li>
      <% end %>
    </ul>
  </section>
</nav>